name: docker

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [native, aarch64_be-unknown-linux-gnu, arm-unknown-eabi]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build CIF
      run: make archive/${{ matrix.config }}

    - name: Upload CIF
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config }}-cif
        path: "*.tar.xz"
