name: macos

on: [push]

jobs:
  build_macos:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Download GCC dependencies
      run: |
        cd aspectator
        ./contrib/download_prerequisites

    - name: Build CIF
      run: make

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Test CIF
      run: |
        python -m pip install --upgrade pytest
        make test

    - name: Archive CIF
      run: tar -cJf $(inst/bin/cif --version).tar.xz -C inst .

    - name: Upload CIF
      uses: actions/upload-artifact@v2
      with:
        name: macos-cif
        path: "*.tar.xz"
